artifact_location: file:C:/Users/ddev/Documents/projects/Customer Onboarding/DocExt/runs/mlflow/862639748616846263
creation_time: 1762112999722
experiment_id: '862639748616846263'
last_update_time: 1762112999722
lifecycle_stage: active
name: /Shared/Ultralytics
