artifact_location: file:C:/Users/ddev/Documents/projects/Customer Onboarding/DocExt/runs/mlflow/0
creation_time: 1762112999681
experiment_id: '0'
last_update_time: 1762112999681
lifecycle_stage: active
name: Default
